import Head from 'next/head';
import Container from 'components/atoms/Container';
import Button from 'components/atoms/Button';
import Link from 'next/link';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Container>
          <Link href="/form">
            <Button as="a">Go to form page</Button>
          </Link>
        </Container>
      </main>
    </div>
  );
}
